name: CI

on:
  push:
    branches:
      - feature/app-code
    paths-ignore:
      - 'helm/**'
      - 'k8s/**'  

jobs:
  build-and-push-jar-github-packages:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Build with Maven
        run: mvn -B clean package --file pom.xml

      - name: Upload JAR artifact  
        uses: actions/upload-artifact@v4
        with:
          name: my-javaapp-jar
          path: target/*.jar
          retention-days: 3

      - name: Publish to GitHub Packages Apache Maven
        run: mvn -B -e deploy -s $GITHUB_WORKSPACE/.m2/settings.xml
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
  
  build-and-push-docker-image-ecr:
    runs-on: ubuntu-latest
    needs: build-and-push-jar-github-packages

    permissions:
      # contents: read
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Download JAR
        uses: actions/download-artifact@v4
        with:
          name: my-javaapp-jar
          path: target

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push Docker image
        env:
          # REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
          IMAGE_TAG: ${{github.run_id}}
        run: |
          echo "Building Docker image..."
          docker build -t $REPOSITORY:$IMAGE_TAG .
          docker tag $REPOSITORY:$IMAGE_TAG $REPOSITORY:latest
          echo "Pushing Docker image to ECR..."
          docker push $REPOSITORY:$IMAGE_TAG
          docker push $REPOSITORY:latest

      - name: Show pushed image info
        run: |
          echo "Image pushed: $REPOSITORY:$IMAGE_TAG"
          echo "Also tagged as latest"
  
  update-newtag-in-helm-chart:
    runs-on: ubuntu-latest

    needs: build-and-push

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          token: ${{ secrets.ACCESS_TOKEN }}

      - name: Update tag in Helm chart
        run: |
          sed -i 's/tag: .*/tag: "${{github.run_id}}"/' helm/my-javaapp/values.yaml

      - name: Commit and push changes
        run: |
          git config --global user.email "caderrimas1999@gmail.com"
          git config --global user.name "Cader Rimas"
          git add helm/my-javaapp/values.yaml
          git commit -m "Update tag in Helm chart"
          git push