name: CI

on:
  push:
    branches:
      - feature/app-code
    paths-ignore:
      - 'helm/**'
      - 'k8s/**'  

jobs:
  build-and-push-github-packages:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'

      - name: Build with Maven
        run: mvn -B clean package --file pom.xml

      - name: Upload JAR artifact  
        uses: actions/upload-artifact@v4
        with:
          name: my-javaapp-jar
          path: target/*.jar
          retention-days: 3

      - name: Publish to GitHub Packages Apache Maven
        run: mvn -B -e deploy -s $GITHUB_WORKSPACE/.m2/settings.xml
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}